### ISSUE TITLE
Implement an AVL tree

### ISSUE THREAD

**Issue by xorz57** [xorz57/forest#14]

**Comment by sauravvishal8797** [comment]
Can this be done in Java?

**Comment by xorz57** [comment]
@sauravvishal8797 Unfortunately no, this is a C++ Library.

**Comment by tejas2005** [comment]
Hi, @xorz57 , can you tell which functions you need in this implementation.

**Comment by xorz57** [comment]
The following functions are absolutely necessary
- Insert
- Delete
- Search

Check the implementation of the other data structures implemented and try to follow the coding style or even fix the coding style of them as well if you have any suggestions! 😃

**Comment by tejas2005** [comment]
@xorz57 can you please provide a link to your code on github

**Comment by xorz57** [comment]
@tejas2005 Sure! https://github.com/xorz57/forest

**Comment by goyaljai** [comment]
i would like to contribute. thanks

**Comment by Vehemos** [comment]
I would like to contribute to this. Thanks!

**Comment by dubielt1** [comment]
Added in #31
