### ISSUE TITLE
(Key and Value) or just (Key) Template Arguments?

### ISSUE THREAD

**Issue by xorz57** [xorz57/forest#15]
I was thinking that just the key is enough for the all the implemented tree data structures because the programmer that will use the library will be able to overload some operators and achieve the same result as if the value was separate from the key.

Do you think there is any point in keeping both key and value?

**Comment by ADSmarcossobral** [comment]
The value is interesting, because one key differs from the others, it would be nice to have more than one value equal in the tree, but different identities.

**Comment by xorz57** [comment]
@ADSmarcossobral So you are in favor of having both key and value. Right?

**Comment by xorz57** [comment]
Another thing I would like to mention is that all data structures here do not allow the insertion of a node with an already existing key. I guess I will have to document this too ...

**Comment by ADSmarcossobral** [comment]
@xorz57 Yes. I do!
