### ISSUE TITLE
Suggestions for better folder structure

### ISSUE THREAD

**Issue by xorz57** [xorz57/forest#16]
### Questions I have
- Should we rename the folder containing the headers to "include" instead of "forest"?
- Should we separate the nodes from the data structures?

### What are your recommendations?

**Comment by goyaljai** [comment]
yes I think "include" would be more good.
no its not needed to seperate nodes from the data structures

**Comment by xorz57** [comment]
@goyaljai Yeah maybe it's better that way I will rename it as soon as there are no active forks and pull requests just to reduce the merge conflicts (I HATE THOSE) 😆

**Comment by goyaljai** [comment]
haha -force works good. Even I hate them ROFL

**Comment by jevans8190** [comment]
What about having abstract base classes for the trees and their nodes to implement?

**Comment by xorz57** [comment]
@jevans8190 I think it will sacrifice code readability for better folder structure. I tried once to have template classes with template class inheritance from an abstract class template and I failed miserably. Appart from that, the headers are portable unless we have abstract template classes.
