### ISSUE TITLE
Need help setting up Continuous Integration for running unit tests

### ISSUE THREAD

**Issue by xorz57** [xorz57/forest#20]

**Comment by zackharley** [comment]
What CI service do you hope to use?

**Comment by xorz57** [comment]
I think Travis CI would be nice! But if you have any recommendations I am all ears!

**Comment by zackharley** [comment]
Awesome. What command do you run to execute your tests?

**Comment by zackharley** [comment]
Also, do you want a CI build to be triggered when a PR is made?

**Comment by xorz57** [comment]
@zackharley that's a bit of a concern... I haven't got any CMakeLists.txt for building the tests yet ... I have created another issue addressing that I need some sort of build system for the tests if you want to check it out too! And yeah I think it would be nice to trigger a CI build when a pr is made ;) I am new to continuous integration and build systems. I hope I will learn a lot from you guys!!!

**Comment by xorz57** [comment]
@zackharley someone is working on the Build System 😃  https://github.com/JLospinoso/forest/commit/e6f6887affc1fb3657d7b077c624eddca82e23ab

**Comment by xorz57** [comment]
@zackharley So, what do you think?

**Comment by JLospinoso** [comment]
@zackharley @xorz57 Project is dockerized, so if you prefer Travis CI should be easier now! https://github.com/xorz57/forest/pull/21

**Comment by xorz57** [comment]
@zackharley I would like your help. Can you trigger a Circle CI build when a PR is made?
