### ISSUE TITLE
Set up Circle CI account, update README with correct badge information

### ISSUE THREAD

**Issue by JLospinoso** [xorz57/forest#22]
Right now the badge reads:

```
[![CircleCI](https://circleci.com/gh/JLospinoso/forest/tree/master.svg?style=svg)](https://circleci.com/gh/JLospinoso/forest/tree/master)
```

After setting up your own account and adding *forest* as a build project, you'll update this URL and the badge will track your builds.

Use the *old* CircleCI build v1. It will read the `circle.yml` and all should just work!

**Comment by JLospinoso** [comment]
@xorz57 Also add hacktoberfest label :)

**Comment by xorz57** [comment]
Again! Thank you!!!
