### ISSUE TITLE
Implement node deletion given a key for the Binary Search Tree

### ISSUE THREAD

**Issue by xorz57** [xorz57/forest#25]

**Comment by goyaljai** [comment]
help me sending you pull request on a new branch :D thanks

**Comment by xorz57** [comment]
I will create an empty function for all node deletions soon

**Comment by Vehemos** [comment]
I would like to contribute to this.

**Comment by MahmoudSirano** [comment]
i have implemented the function, but how can i contribute?, im kind of newbie

**Comment by xorz57** [comment]
@MahmoudSirano 
1. Fork this repository.
2. Create a feature branch on the develop branch with your changes.
3. Make your commits on that branch instead of master and develop.
4. When done, start a pull request from that branch to the original develop branch.
