### ISSUE TITLE
Implement node deletion given a key for the Red Black Tree

### ISSUE THREAD

**Issue by xorz57** [xorz57/forest#26]
Parameters: **ONLY** the key of the node to be deleted
Return Value: **void**

**Comment by rosemilk** [comment]
@xorz57 I'd like to help with this. Thanks

**Comment by xorz57** [comment]
@rosemilk I will create an empty function for all node deletions soon

**Comment by Vehemos** [comment]
I would like to contribute to this.

**Comment by ADSmarcossobral** [comment]
I would like to contribute to this. I already implemented the code. I am waiting to make the pull request. @xorz57
