### ISSUE TITLE
Implement node deletion given a key for the Splay Tree

### ISSUE THREAD

**Issue by xorz57** [xorz57/forest#27]
Parameters: **ONLY** the key of the node to be deleted
Return Value: **void**

**Comment by rosemilk** [comment]
@xorz57 I'd like to help with this.

**Comment by xorz57** [comment]
@rosemilk I will create an empty function for all node deletions soon

**Comment by Vehemos** [comment]
I would like to contribute to this.

**Comment by ADSmarcossobral** [comment]
Hi, I would like to contribute to this. @xorz57
