### ISSUE TITLE
Create a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by xorz57** [xorz57/forest#36]
I am sorry this is a draft text ✉️ 
So far I have postponed something very important. The CONTRIBUTING.md file.
I would like some help composing the containing text and making it look beautiful yet simple.

Here is what I expect from anyone who wants to contribute to this repository.
8 spaces for indentation
lower-case variable names, using underscores to separate words
always prefer iterative implementations instead of recursive ones
comment your code
test your code
try to follow the git flow instead of the github flow (I am having trouble merging pull requests from lots of people. more information on this will be available soon)

**Comment by ms10398** [comment]
I would like to work on this issue

**Comment by animeshsrivastava24** [comment]
I am enthusiastic to work on this issue.

**Comment by xorz57** [comment]
Another user provided a solution so I am closing this pull request.
