### ISSUE TITLE
Tree Conversions

### ISSUE THREAD

**Issue by xorz57** [xorz57/forest#41]
The idea is to provide a way to copy all the nodes from any tree from one data structure to any other tree.

**Comment by dubielt1** [comment]
This would probably be best implemented marking all classes as friends to one another, since root is private. Do you agree?

Then something like:
binary_search_tree<int,int> b = {nice full tree}
avl_tree<int,int> a(std::move(b));

That way each class would only need to implement a move constructor

**Comment by xorz57** [comment]
@dubielt1 Well, that's a start 👍 I guess we have to try some things out and see what works best.

I started this project while reading the book C++ Primer - 5th Edition. I am still new to C++ so I have to get to know better what C++ offers as far as object-oriented programming is concerned. 🚶
