### ISSUE TITLE
Replace raw pointers inside avl_tree.h with smart pointers

### ISSUE THREAD

**Issue by xorz57** [xorz57/forest#44]
Appart from that, I would like some help porting the predecessor and successor member functions to the other data structures as well.

**Comment by xorz57** [comment]
@MatusKysel I thought you might be interested in this.

**Comment by MatthiasKauer** [comment]
Hi,
What do you have in mind here? unique_ptr should be preferred over shared_ptr, I suppose.
Do you already foresee challenges?

**Comment by xorz57** [comment]
@MatthiasKauer In general, whatever is faster is better. I guess we could check the performance using shared pointers in comparison to using unique pointers. I have also tagged @MatusKysel who converted entirely the raw pointers for 3 of the data structures to smart pointers.

**Comment by MatusKysel** [comment]
I have chosen shared_ptr, because binary trees are recursive by definition and in that case, I think shared ownership is better. Of course shared_ptr has some overhead compared to unique_ptr, but I do not think that it has significant cost on overall performance.

**Comment by xorz57** [comment]
@MatusKysel I see what you mean. Do you know if it is possible to port the successor and predecessor functions to the other data structures that use smart pointers? Is this possible? I tried doing that but totally failed 😆 . I am new to the C++11 standard, still reading C++ Primer 5th edition.

**Comment by MatusKysel** [comment]
I did not have a lot of time lately, but there you go PR
