### ISSUE TITLE
Better CMakeLists.txt

### ISSUE THREAD

**Issue by xorz57** [xorz57/forest#48]
- Use [modern cmake](https://www.youtube.com/watch?v=bsXLMQ6WgIk) and avoid deprecated commands
- Keep it Simple
- Add support for Visual Studio Project
- Make installation of the header files possible on Windows OS

NOTICE: Be sure to reconfigure the CI as well if you make any incompatible changes.

**Comment by light2yellow** [comment]
I would like to help with it except Windows-related work. I have no idea about Windows.

**Comment by xorz57** [comment]
@light2yellow Yup. Go for it :) The library is header only anyways so windows users can just include the header files.

**Comment by xorz57** [comment]
Another thing I would like to mention is if possible, remove the catch.hpp from the tests and download it automatically from its github repository before building the tests.

**Comment by light2yellow** [comment]
> Another thing I would like to mention is if possible, remove the catch.hpp from the tests and download it automatically from its github repository before building the tests.

Oh, I completely forgot about it. I'll try to address it though.

**Comment by xorz57** [comment]
@light2yellow If you can turn off building the doxygen documentation from the Dockerfile because I haven't found a way to install doxygen and graphviz into the docker image as well.

**Comment by light2yellow** [comment]
I'll try experimenting with CircleCI and Dockerfile on my fork and see if I can accomplish it (if not, I'll remove it).

**Comment by xorz57** [comment]
I think the docker file should be modified like this
```
FROM quay.io/jlospinoso/cppbuild:v1.0.0

RUN mkdir forest
WORKDIR forest
COPY / ./
RUN mkdir build
WORKDIR build
RUN apt install -y doxygen
RUN apt install -y graphviz
RUN cmake -DFOREST_BUILD_EXAMPLES=ON -DFOREST_ENABLE_TESTING=ON -DFOREST_BUILD_DOCUMENTATION=ON ..
RUN make examples
RUN make check
RUN make doc
```
I don't have time to verify the validity of this right now because I am busy studying at the university this week.
