### ISSUE TITLE
Create Benchmarks

### ISSUE THREAD

**Issue by xorz57** [xorz57/forest#63]
It would be nice if we could have some benchmarking done for most if not all tree data structures.

**Comment by tellenbach** [comment]
Hello,

I recommend to use the Google benchmark library [google/benchmark](https://github.com/google/benchmark). It is of high quality and widely used. If you want, I could create, run and visualise some benchmarks.

Cheers,
David

**Comment by tellenbach** [comment]
Hello,

I've run a first benchmark and it doesn't look too good. I filled a ``forest::binary_search_tree`` with up to ``10000`` elements and searched for an element that is located near the end of the tree. To compare the results I used a ``std::map`` which provides a tree like access structure and ``std::vector``. For the latter I just looped through the ``std::vector`` until I found the element.

```
--------------------------------------------------------------------------
Benchmark                                   Time           CPU Iterations
--------------------------------------------------------------------------
BM_STL_VECTOR/1000                        212 ns        212 ns    3082831
BM_STL_VECTOR/2000                        459 ns        458 ns    1694542
BM_STL_VECTOR/3000                        646 ns        646 ns     962027
BM_STL_VECTOR/4000                        802 ns        802 ns     842683
BM_STL_VECTOR/5000                       1009 ns       1009 ns     636769
BM_STL_VECTOR/6000                       1199 ns       1199 ns     552003
BM_STL_VECTOR/7000                       1405 ns       1405 ns     491874
BM_STL_VECTOR/8000                       1769 ns       1758 ns     419662
BM_STL_VECTOR/9000                       2083 ns       2078 ns     331559
BM_STL_VECTOR/10000                      2142 ns       2140 ns     306070
BM_STL_MAP/1000                            33 ns         33 ns   21346475
BM_STL_MAP/2000                            39 ns         39 ns   17570237
BM_STL_MAP/3000                            43 ns         43 ns   15762890
BM_STL_MAP/4000                            46 ns         46 ns   13755158
BM_STL_MAP/5000                            53 ns         53 ns   12495983
BM_STL_MAP/6000                            53 ns         53 ns   13294084
BM_STL_MAP/7000                            73 ns         73 ns    9221932
BM_STL_MAP/8000                            95 ns         95 ns    7361060
BM_STL_MAP/9000                            79 ns         79 ns    7056167
BM_STL_MAP/10000                          101 ns        101 ns    7059156
BM_FOREST_BINARY_SEARCH_TREE/1000       11318 ns      11315 ns      64297
BM_FOREST_BINARY_SEARCH_TREE/2000       24231 ns      24196 ns      27306
BM_FOREST_BINARY_SEARCH_TREE/3000       34556 ns      34550 ns      18923
BM_FOREST_BINARY_SEARCH_TREE/4000       45267 ns      45259 ns      15307
BM_FOREST_BINARY_SEARCH_TREE/5000       57977 ns      57968 ns      12684
BM_FOREST_BINARY_SEARCH_TREE/6000       71488 ns      71469 ns       9996
BM_FOREST_BINARY_SEARCH_TREE/7000       83048 ns      83003 ns       8997
BM_FOREST_BINARY_SEARCH_TREE/8000       94315 ns      94258 ns       7353
BM_FOREST_BINARY_SEARCH_TREE/9000      103364 ns     103317 ns       6987
BM_FOREST_BINARY_SEARCH_TREE/10000     116531 ns     116522 ns       5700
```

![benchmark](https://user-images.githubusercontent.com/23486477/41142762-29d5352a-6af7-11e8-8c59-ab4c1543f412.png)

The example is compiled using ``Apple LLVM version 9.1.0 (clang-902.0.39.2)`` and the ``-O3`` flag.

**Comment by xorz57** [comment]
@tellenbach I just watched this video on CppCon. Are you sure about the benchmarks accuracy of `std::vector` and `std::map`?

https://www.youtube.com/watch?v=nXaxk27zwlk

**Comment by tellenbach** [comment]
1. To be clear: ``std::vector`` is much slower than ``std::map`` but ``binary_search_tree`` is so much slower that you cannot see this big difference here. The graph below shows the same data without the measurement of ``binary_search_tree``. 

![benchmark](https://user-images.githubusercontent.com/23486477/41156587-ddd42218-6b22-11e8-941c-1d934daf4a21.png)

2. I'm measuring different things than Chandler does in his talk. I wanted to measure the thing binary trees are usually good at: Searching. Therefore the measurement does not take construction of the objects into account. E.g. the benchmark for ``binary_search_tree`` looks like this

```c++
static void BM_FOREST_BINARY_SEARCH_TREE(benchmark::State& state) {
  forest::binary_search_tree <int, int> binary_search_tree;

  for (int i = 0; i < state.range(0); ++i) {
    binary_search_tree.insert(i, i * 2);
  }

  // Measurement happens inside of this loop
  for (auto _ : state) {
    auto search = binary_search_tree.search(state.range(0) - 2);
  }
}
```

**Comment by xorz57** [comment]
@tellenbach Nice!!! By the way `forest::binary_search_tree` does not rebalance itself so searching is definitely slower if the tree is not balanced.

**Comment by xorz57** [comment]
I just run a couple of benchmarks on some functions.
Note: Only worst case scenario search time shown.
![image](https://user-images.githubusercontent.com/1548352/41198236-46fb360e-6c7d-11e8-82a9-a6b8e8b5de60.png)
![image](https://user-images.githubusercontent.com/1548352/41198240-563a6afe-6c7d-11e8-9ea2-c29fde98b50e.png)
![image](https://user-images.githubusercontent.com/1548352/41198243-5cfbcbd0-6c7d-11e8-9e73-10e04ec0fd17.png)
![image](https://user-images.githubusercontent.com/1548352/41198245-6d84b75a-6c7d-11e8-9ae3-23c5988deef0.png)

**Comment by xorz57** [comment]
@tellenbach By the way how do you plot the benchmark data? I guess you are using python to do that, if so what library?

**Comment by tellenbach** [comment]
@xorz57 Great! I've tried searching using AVL and red black trees and the performance is much better than in the case of unbalanced trees. 

To visualize benchmarks I use the following Python script I've created: https://github.com/tellenbach/BenchmarkVisualizer

**Comment by xorz57** [comment]
![image](https://user-images.githubusercontent.com/1548352/41227528-d3303b32-6d7d-11e8-9b8b-a6730742ddce.png)
Does not look that bad but we have not beaten STL 😆

**Comment by xorz57** [comment]
![search - worst case](https://user-images.githubusercontent.com/1548352/41383323-de86edb2-6f78-11e8-95e8-3c1a56970958.png)

@tellenbach When I have the time I will write the CMakeLists.txt for the benchmarks and upload a benchmarks folder with the source code.
