### ISSUE TITLE
Ability to return the root of the trees

### ISSUE THREAD

**Issue by xorz57** [xorz57/forest#74]
How should I name such a function? If I stick with the obvious answer `root` then I will have to rename the private member variable `root` to something else.

**Comment by tellenbach** [comment]
Some projects I've contributed to used some prefix like ``m_`` for (private) member variables. In this case the variable ``root`` would then be refactored to ``m_root``.
If you want to avoid name changes at all something like ``tree_root`` could work.

**Comment by xorz57** [comment]
@tellenbach Looks neat :+1: I will try doing that.

**Comment by xorz57** [comment]
Done
