### ISSUE TITLE
[Red Black Tree] Implement Remove Operation

### ISSUE THREAD

**Issue by xorz57** [xorz57/forest#86]
#### [Wikipedia](https://en.wikipedia.org/wiki/Red%E2%80%93black_tree)

**Comment by ananya1304** [comment]
I would like to take up this issue.

**Comment by xorz57** [comment]
@ananya1304 Nice to hear that!!!

**Comment by xorz57** [comment]
This data structure will be deleted soon if no delete operation is implemented.
