### ISSUE TITLE
Implement Node Deletion Operation for all tree data structures

### ISSUE THREAD

**Issue by xorz57** [xorz57/forest#9]
This operation should remove a node given its key from following tree data structures:
- Binary Search Tree
- Splay Tree
- Red Black Tree

**Comment by cjlcarvalho** [comment]
@xorz57

**Comment by alangberg** [comment]
Hello, What tree data structures in particular? I can help with binary search tree, avl, heap, red black tree, etc.

**Comment by xorz57** [comment]
First of all i would like to welcome you to this project :) Yeah the project has a red black tree a splay tree and a binary search tree. All trees must be tested with some kind of unit test framework (I am using catch but any suggestions are welcome :) )

**Comment by goyaljai** [comment]
i would like to contribute. thanks

**Comment by xorz57** [comment]
@goyaljai Much appreciated !!!

**Comment by goyaljai** [comment]
thanks, can you explain a bit? how to start and how and where to add the code? thanks

**Comment by xorz57** [comment]
@goyaljai The project's structure is fairly simple
- **doc** contains a doxygen file that will generate the documentation of our project
- **tests** contains test cases for all data structures testing all features (every new feature must be tested). I will make it more clear in a couple of days.
- **forest** contains all the data structures source code (these are all header files only)
- **examples** contains (you guessed it) examples using the library

**Comment by goyaljai** [comment]
i have implemented BST's delete. and followed your code structure. should i send you a pull request?

**Comment by xorz57** [comment]
@goyaljai Yup! go for it!

**Comment by xorz57** [comment]
@goyaljai @alangberg @cjlcarvalho 
Guys, I am splitting this issue for every data structure available so that you get the chance to start your pull requests faster.
